# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('AUDI', 'Audi'), ('MERCEDES', 'Mercedes'), ('BMW', 'BMW'), ('FERRARI', 'Ferrari'), ('SKODA', 'Skoda'), ('KIA', 'Kia')], default='', max_length=50)),
                ('year', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('model', models.TextField(default='Other', max_length=60)),
            ],
        ),
    ]
