# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardealership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date(2018, 10, 7), verbose_name='Start Date')),
                ('end_date', models.DateField(default=datetime.date(2018, 10, 8), verbose_name='End Date')),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DateField(default=2018, verbose_name='year'),
        ),
        migrations.AddField(
            model_name='rental',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardealership.Car'),
        ),
    ]
