# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 20:12
from __future__ import unicode_literals

import cardealership.cardealership.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardealership', '0002_auto_20181007_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2018, validators=[django.core.validators.MinValueValidator(1984), cardealership.cardealership.models.max_value_current_year], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='end_date',
            field=models.DateField(default=datetime.date(2018, 10, 9), verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 10, 8), verbose_name='Start Date'),
        ),
    ]
